/**
 * Export utilities for CSV and simple PDF downloads.
 * No external dependencies — uses browser APIs only.
 */

/** Download a string as a file */
function downloadBlob(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/** Escape a CSV cell value */
function csvEscape(value: string | number | null | undefined): string {
  const s = value === null || value === undefined ? '' : String(value);
  if (s.includes(',') || s.includes('"') || s.includes('\n')) {
    return '"' + s.replace(/"/g, '""') + '"';
  }
  return s;
}

/** Export an array of objects as CSV */
export function exportCsv(
  rows: Record<string, string | number | null | undefined>[],
  filename: string,
  headers?: string[]
) {
  if (rows.length === 0) return;
  const keys = headers ?? Object.keys(rows[0]);
  const csvRows = [
    keys.join(','),
    ...rows.map(row => keys.map(k => csvEscape(row[k])).join(',')),
  ];
  downloadBlob(csvRows.join('\n'), filename, 'text/csv;charset=utf-8;');
}

/** Export content as a simple text-based "report" PDF using print */
export function exportPdfViaPrint(title: string) {
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    alert('Please allow popups to generate the PDF.');
    return;
  }
  // Get the main content area
  const content = document.querySelector('.flex-1.overflow-y-auto');
  if (!content) return;

  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>${title}</title>
      <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&family=DM+Mono:wght@400;500&display=swap');
        body { font-family: 'Inter', sans-serif; color: #0a1628; padding: 40px; max-width: 900px; margin: 0 auto; }
        h1 { font-size: 20px; color: #1a3a5c; margin-bottom: 4px; }
        .subtitle { font-size: 12px; color: #64748b; margin-bottom: 24px; }
        table { width: 100%; border-collapse: collapse; margin: 16px 0; }
        th { background: #f4f6f8; padding: 8px 12px; text-align: left; font-size: 10px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.8px; color: #64748b; border-bottom: 2px solid #e2e8f0; }
        td { padding: 10px 12px; font-size: 12px; border-bottom: 1px solid #e2e8f0; }
        .mono { font-family: 'DM Mono', monospace; }
        .tag { display: inline-block; font-size: 9px; font-weight: 700; padding: 2px 8px; border-radius: 12px; text-transform: uppercase; }
        .tag-pass { background: #eafaf2; color: #15803d; }
        .tag-warn { background: #fffbeb; color: #a16207; }
        .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 10px; color: #64748b; }
        @media print { body { padding: 20px; } }
      </style>
    </head>
    <body>
      <h1>${title}</h1>
      <div class="subtitle">Town of Alma · Generated ${new Date().toLocaleString()}</div>
      ${content.innerHTML}
      <div class="footer">Generated by Upstream AI · ${new Date().toLocaleDateString()}</div>
    </body>
    </html>
  `);
  printWindow.document.close();
  setTimeout(() => printWindow.print(), 500);
}

/** Generate an iCal (.ics) file */
export function exportICal(events: { title: string; date: string; description?: string }[], filename: string) {
  const lines = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//Upstream AI//Compliance Calendar//EN',
    ...events.flatMap(e => [
      'BEGIN:VEVENT',
      `DTSTART;VALUE=DATE:${e.date.replace(/-/g, '')}`,
      `SUMMARY:${e.title}`,
      e.description ? `DESCRIPTION:${e.description}` : '',
      `UID:${crypto.randomUUID()}@upstream.ai`,
      'END:VEVENT',
    ].filter(Boolean)),
    'END:VCALENDAR',
  ];
  downloadBlob(lines.join('\r\n'), filename, 'text/calendar;charset=utf-8');
}

/** Show a toast-style notification */
export function showToast(message: string) {
  const toast = document.createElement('div');
  toast.textContent = message;
  toast.style.cssText = `
    position: fixed; bottom: 24px; right: 24px; z-index: 9999;
    background: #1a3a5c; color: white; padding: 12px 20px;
    border-radius: 10px; font-size: 13px; font-weight: 600;
    font-family: Inter, sans-serif; box-shadow: 0 8px 24px rgba(0,0,0,0.2);
    animation: fadeIn 0.2s ease-out;
  `;
  document.body.appendChild(toast);
  setTimeout(() => {
    toast.style.opacity = '0';
    toast.style.transition = 'opacity 0.3s';
    setTimeout(() => document.body.removeChild(toast), 300);
  }, 2500);
}
